### ISSUE TITLE
Wrong example in `subtyping.md`?

### ISSUE THREAD

**Issue by jimblandy** [rust-lang-nursery/nomicon#98]
The subtyping section has the following text:

> If mutation is by-value, then the old location that remembers extra details is moved out of, meaning it can't use the value anymore. So we simply don't need to worry about anyone remembering dangerous details. Put another way, applying subtyping when passing by-value destroys details forever. For example, this compiles and is fine:
>
>     fn get_box<'a>(str: &'a str) -> Box<&'a str> {
>         // String literals are `&'static str`s, but it's fine for us to
>         // "forget" this and let the caller think the string won't live that long.
>         Box::new("hello")
>     }
>
> If mutation is by-reference, then our container is passed as `&mut Vec<T>`. But `&mut` is invariant over its value, so `&mut Vec<T>` is actually invariant over `T`. So the fact that `Vec<T>` is covariant over `T` doesn't matter at all when mutating by-reference.

Explanations of subtyping always push me to my limit, so when I can't see how the example relates to the discussion, my first assumption is *not* "Oh, the text is wrong"! But I suspect that the example here is just the wrong text, because there's no mutation going on anywhere, nor any `&mut Vec<T>`.

**Comment by Gankro** [comment]
Ah, interesting. We could definitely do with a better example here. And yeah following text should refer to the same type and also probably have its own example.

I will however assert the example is both correct and relevant to the text that precedes it. It takes a `Box<'static>` and passes it by-value (by returning it) to someone expecting a `Box<'a>`. This is only sound because passing the Box by-value is a statically verified assertion that no one else has access to the Box, and therefore no one exists who remembers the Box is "supposed" to be 'static. 

This is in contrast to e.g. Java where having a `MyType<Animal>` tells you nothing about who else may have access to that value, and so it would be unsound to construct such a type by "forgetting" that it was a `MyType<Cat>`, because `MyType<Animal>` implies that a `Dog` should be fine to store inside, which will break anyone who knows a `Cat` should be there.

**Comment by Gankro** [comment]
this chapter was completely rewritten and is much clearer now.
